#!/usr/bin/env python3
"""Pilot (LinkedIn carousel): build a LinkedIn document-post carousel.

Driven by the linkedin-studio soul, on Opus 4.8 via OpenRouter. PORTRAIT 4:5
slides (1080x1350) -> one self-contained HTML document -> Playwright print PDF
(LinkedIn documents are PDFs) plus per-slide preview PNGs. Real facts only;
never prints API keys.

The SYSTEM prompt is assembled from the profile so the carousel is GENERATED by
the soul + the model, not hand-authored:
  1. soul:         ~/.hermes/profiles/linkedin-studio/SOUL.md
  2. constitution: ~/.hermes/profiles/linkedin-studio/references/DESIGN-OS.md
  3. SOP:          ~/.hermes/profiles/linkedin-studio/skills/linkedin-asset-production/SKILL.md
plus the hard OUTPUT CONTRACT below.

Examples
--------
    uv run --no-project python factory/scripts/pilot_linkedin_carousel_generate.py --client aa
    uv run --no-project python factory/scripts/pilot_linkedin_carousel_generate.py --client inspra
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERMES = Path.home() / ".hermes"
PROFILE = HERMES / "profiles" / "linkedin-studio"
API_BASE = "https://openrouter.ai/api/v1"


# ---------------------------------------------------------------------------
# Profile -> SYSTEM prompt.
# ---------------------------------------------------------------------------

# The hard contract for a LinkedIn document-post carousel. Appended after the
# soul + the constitution non-negotiables so the model cannot drift on specs.
OUTPUT_CONTRACT = """
=== OUTPUT CONTRACT (LinkedIn document-post carousel) — non-negotiable ===
- Output ONE complete self-contained HTML document only (inline <style>; minimal vanilla <script> only if strictly needed). Begin with <!DOCTYPE html>. No markdown, no commentary, no code fences.
- PORTRAIT slides, 1080px x 1350px (4:5 — max mobile reach). CSS: @page { size: 1080px 1350px; margin: 0 }. html,body { margin:0; padding:0 }.
- EXACTLY 8 slides. Each slide is <section class="slide"> sized EXACTLY 1080px x 1350px, position:relative, overflow:hidden, box-sizing:border-box, and break-after:page on every slide EXCEPT the last (the last must NOT force a trailing blank page). Design each slide as one complete composition; never overflow a slide; keep all content inside an 80px safe margin.
- Slide 1 = a scroll-stopping HOOK: a bold, specific claim OR a single REAL stat from the supplied facts (never invented), the brand logo, very high contrast, and a swipe cue ("Swipe ->" or an arrow). No generic "Tips for X" / "Did you know?".
- Middle slides (2-7) = ONE idea per slide, a useful and specific sequence drawn from the client positioning. Persistent progress cue ("3/8") and bridging phrases ("Here is why", "The result"). Alternate text-led and visual-led; identical grid, fonts and colours across every slide.
- Slide 8 = a clear CTA: restate the one takeaway + one concrete action (book / comment / follow / visit) + the brand mark. A question lifts comments.
- Mobile-feed legibility floor: headings large and confident (>=48px design size), body >=24px, <=6-8 lines and <=60 words per slide, contrast >=4.5:1 (WCAG AA on every text/background pair), palette <=3-4 brand colours, generous white space.
- ALL text is real HTML. Icons are monoline inline SVG (stroke ~1.7px, currentColor), NEVER emoji, NEVER symbol glyphs. WCAG AA contrast on dark and light.
- The logo is provided as a real file at assets/<logo-file> — reference it as <img src="assets/<logo-file>" ...> with a sensible pixel height; do NOT bake any text into an image, do NOT use placeholder/stock image CDNs, do NOT invent a logo.
- One ownable distinctive move carried across all 8 slides (a motif from the brand, an opinionated type decision, an editorial primitive) so an outsider can tell which brand a single slide belongs to.
- Honesty: use ONLY the real facts supplied in the USER message. Invent no metrics, percentages, dollar figures, client counts, awards, names, quotes or certifications. Australian English, no US spellings, no contractions, no em/en-dash punctuation. Avoid banned words (revolutionary, game-changing, streamline, empower, seamless, unlock, elevate, leverage, cutting-edge, world-class, best-in-class, all-in-one, delve, tapestry, testament, boasts).
- Do NOT use: default indigo/purple AI accents (#6366f1 #4f46e5 #8b5cf6 #7c3aed etc.), a two-stop purple/blue/cyan "AI" gradient, gradient-clip text on headings/metrics, rounded cards with a thick coloured left-border, emoji icons, Inter/Roboto/Arial/Geist/Space Grotesk as the signature display face.

Return ONLY the complete HTML document, beginning with <!DOCTYPE html>.
"""


def build_system() -> str:
    """Assemble SYSTEM = soul + constitution non-negotiables + SOP anatomy + contract."""
    soul = (PROFILE / "SOUL.md").read_text(encoding="utf-8").strip()
    constitution = (PROFILE / "references" / "DESIGN-OS.md").read_text(encoding="utf-8").strip()
    sop = (PROFILE / "skills" / "linkedin-asset-production" / "SKILL.md").read_text(
        encoding="utf-8"
    ).strip()
    return (
        "You are linkedin-studio, generating a client-grade LinkedIn carousel "
        "(document post) end to end. You inherit the Hermes Design Factory "
        "constitution and your own production SOP, reproduced below. Follow the "
        "non-negotiables (facts before layout, never invent proof, real text "
        "stays real HTML/SVG, accessibility, honesty/banned-words) and the "
        "carousel anatomy exactly.\n\n"
        "===== SOUL (linkedin-studio) =====\n"
        f"{soul}\n\n"
        "===== CONSTITUTION (DESIGN-OS — the floor, not overridable) =====\n"
        f"{constitution}\n\n"
        "===== PRODUCTION SOP (linkedin-asset-production) =====\n"
        f"{sop}\n"
        f"{OUTPUT_CONTRACT}"
    )


# ---------------------------------------------------------------------------
# Per-client briefs (real facts only — drawn verbatim from source-truth).
# ---------------------------------------------------------------------------

CLIENTS = {
    "aa": {
        "slug": "automate-accelerator",
        "title": "Automate Accelerator LinkedIn carousel",
        "x_title": "Design Hermes Pilot AA LinkedIn Carousel",
        "logo_src": ROOT
        / "clients/automate-accelerator/04-production/pilot-v5-bip/assets/aa-logo.png",
        "logo_file": "aa-logo.png",
        "source_truth": ROOT / "clients/automate-accelerator/02-source-truth",
        "user": """Build the Automate Accelerator LinkedIn carousel (8 portrait slides, 1080x1350) for the FOUNDER profile, using ONLY this real content.

BRAND: Automate Accelerator — an Australian B2B growth company and outbound partner (not an outbound agency). A professional team on payroll runs client campaigns; AI multiplies what the team can do. Voice: confident, accountable, no-fluff, outcome-led.
PALETTE (brand-real, no other accents): --accent #F47920 (orange — the action/highlight colour, <=2 strong uses per slide), --brand #412F8F (purple — brand depth, dark sections, the dotted-matrix motif), --ink #14121A, --bg #FFFFFF, --surface #F6F4FB, --muted #5A5566. Orange is the action colour; purple is brand depth. NEVER a purple-to-blue/cyan AI gradient.
TYPE: clean geometric grotesk via Fontshare https://api.fontshare.com/v2/css?f[]=clash-display@600,700&f[]=general-sans@400,500,600&display=swap — Clash Display for headings, General Sans for body, Arial fallback.
DISTINCTIVE MOVE (carry across all 8 slides): the orange "//" double-slash as a recurring section marker, plus a purple/orange dotted-matrix texture (CSS radial-gradient dots) — the slide must be recognisably Automate Accelerator from a single screenshot.
LOGO: assets/aa-logo.png (place on slide 1 and the final CTA slide; on dark/purple slides keep it legible).

POSITIONING LINES (use, do not alter the meaning): "More qualified meetings. Human expertise. AI where it multiplies." / "The human touch in every outreach, powered by AI precision." / "You show up to the meetings. We do the legwork."

REAL PROOF (use EXACTLY as written; do not round, scale, combine or invent): 850+ Australian businesses served since 2021; 54,486+ successful appointments booked for clients; 70+ B2B industries; 98% client retention rate.

DIFFERENTIATORS (what makes the partner different): no retainer for activity; no bought lists; no outsourcing; a dedicated professional team on payroll; data-backed decisions and a transparent performance model; your brand, your approvals, your data and control.

THE TWO OFFERS: 1) Growth Engine — a professional outbound team plus data, email, LinkedIn and voice outreach, follow-up and nurture, and CRM and reporting. 2) AI Solutions — solution architects and developers build AI inside your existing operations (Discover, Build, Deliver).

SUGGESTED 8-SLIDE SEQUENCE (one idea per slide; you may refine the wording but keep facts exact):
1 HOOK — lead with a real stat (e.g. "54,486+ appointments booked" or "850+ Australian businesses since 2021") + a swipe cue.
2 The problem — referrals plateau; pipeline becomes unpredictable; the usual answer is another agency that takes a retainer and sends a report.
3 The shift — human expertise where it counts, AI where it multiplies; you show up to the meetings, the team does the legwork.
4 What the partner does NOT do — no retainer for activity, no bought lists, no outsourcing (this is the differentiator slide).
5 Growth Engine — the professional outbound team across email, LinkedIn and voice, with follow-up and CRM reporting.
6 AI Solutions — architects and developers build AI inside your existing operations (Discover, Build, Deliver).
7 The proof — the real numbers together: 850+ businesses, 54,486+ appointments, 70+ industries, 98% retention.
8 CTA — "You show up to the meetings. We do the legwork." Book a discovery call. Include the logo.

Return ONLY the complete HTML document.""",
    },
    "inspra": {
        "slug": "inspra-ai",
        "title": "Inspra AI LinkedIn carousel",
        "x_title": "Design Hermes Pilot Inspra LinkedIn Carousel",
        "logo_src": ROOT
        / "clients/inspra-ai/04-production/pilot-v5-bip/assets/inspra-logo-light.png",
        "logo_file": "inspra-logo-light.png",
        "logo_src_dark": ROOT
        / "clients/inspra-ai/04-production/pilot-v5-bip/assets/inspra-logo-dark.png",
        "logo_file_dark": "inspra-logo-dark.png",
        "source_truth": ROOT / "clients/inspra-ai/02-source-truth",
        "user": """Build the Inspra AI LinkedIn carousel (8 portrait slides, 1080x1350) for the FOUNDER profile, using ONLY this real content.

BRAND: Inspra AI (a trading brand of Genius365) — Voice AI agents for Australian businesses. We build, deploy and optimise Voice AI agents that handle phone calls 24/7 with natural, professional Australian conversations, so businesses scale without scaling headcount. Melbourne. ISO 27001 certified. Voice: clear, enterprise-credible, confident.
PALETTE (brand-real, no other accents): --accent #39E100 (signature green — highlights, key numbers, the soundwave motif, CTAs; use it deliberately on dark and on white), --ink #1A1A1A, --bg #FFFFFF, --dark #121212 (dark slides), --surface #F4F7F2, --muted #5A5F58. Green is the brand signal colour. NEVER a generic AI purple-to-blue/cyan gradient.
TYPE: clean modern enterprise grotesk via Fontshare https://api.fontshare.com/v2/css?f[]=switzer@500,600,700&f[]=general-sans@400,500,600&display=swap — Switzer for headings, General Sans for body, Arial fallback.
DISTINCTIVE MOVE (carry across all 8 slides): a green soundwave / waveform line and green signal dots (the voice-AI signature) used as section markers and dividers — the slide must be recognisably Inspra from a single screenshot.
LOGO: assets/inspra-logo-light.png (light logo — use on dark/green slides) and assets/inspra-logo-dark.png (dark logo — use on white slides). Place the logo on slide 1 and the final CTA slide.

POSITIONING: "AI voice agents for business." We build, deploy and optimise Voice AI agents that handle calls 24/7 with natural, professional Australian conversations. Scale without scaling headcount; keep the human touch where it matters while the agents handle the volume.

REAL PROOF (use EXACTLY as written; do not round, scale, combine or invent): 40% increase in conversion; 15x more call outputs; 40% cost reduction in operations; 24/7 operation; 350+ enterprises using the platform; ISO 27001 certified.

THE PROBLEM: missed calls, inconsistent call quality, and expensive staffing for phone-based workflows. Every missed call is a missed customer.

HOW IT WORKS (numbered process): 1 Build — custom voice agents configured for your business, FAQs and flows. 2 Test — battle-tested with real scenarios before go-live. 3 Deploy — go-live with monitoring, call recording and analytics. 4 Optimise — continuous improvement from real call data.

DIFFERENTIATORS: ISO 27001 certified (enterprise-grade security for voice data); Australian-based with Australian voice profiles and local market knowledge; principle-based prompts (higher success than scripted flows); multi-platform (VAPI, Retell AI, LiveKit) — never locked to one provider; scales instantly from 10 to 10,000 calls per day, 24/7.

WHO IT IS FOR: Australian SME and mid-market businesses with high call volumes — real estate, legal, dental, plumbing and trades, B2B sales teams, customer support, appointment-heavy businesses.

SUGGESTED 8-SLIDE SEQUENCE (one idea per slide; you may refine the wording but keep facts exact):
1 HOOK — the cost of missed calls, or a real stat ("15x more call outputs" / "350+ enterprises") + a swipe cue.
2 The problem — missed calls, inconsistent quality, expensive phone staffing; every missed call is a missed customer.
3 The fix — Voice AI agents that handle calls 24/7 with natural Australian conversations; scale without scaling headcount.
4 How it works — the numbered Build, Test, Deploy, Optimise process.
5 The results — the real numbers: 40% more conversion, 15x more call outputs, 40% cost reduction, 24/7.
6 Why Inspra — ISO 27001 certified, Australian voices, principle-based prompts, multi-platform, scales 10 to 10,000 calls a day.
7 Who it is for — Australian SME and mid-market with high call volumes (the industries).
8 CTA — Book a demo. Include the logo and "inspra.ai".

Return ONLY the complete HTML document.""",
    },
}


# ---------------------------------------------------------------------------
# Helpers reused verbatim from the BIP pilot template.
# ---------------------------------------------------------------------------

def load_env() -> None:
    for path in [ROOT / ".env", ROOT / ".env.local", HERMES / ".env",
                 HERMES / "profiles" / "landing-page-studio" / ".env"]:
        if not path.exists():
            continue
        for line in path.read_text(errors="ignore").splitlines():
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            k, v = s.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k and k not in os.environ:
                os.environ[k] = v


def or_key() -> str:
    k = os.getenv("OPENROUTER_API_KEY") or os.getenv("OPENROUTER_KEY") or ""
    if not k.strip():
        raise SystemExit("Missing OPENROUTER_API_KEY")
    return k.strip()


def extract_html(text: str) -> str:
    if not text:
        return ""
    t = text.strip()
    if "```" in t:
        m = re.search(r"```(?:html)?\s*(.*?)```", t, re.S | re.I)
        if m:
            t = m.group(1).strip()
    low = t.lower()
    start = low.find("<!doctype")
    if start == -1:
        start = low.find("<html")
    end = low.rfind("</html>")
    if start != -1 and end != -1:
        return t[start:end + len("</html>")]
    if start != -1:
        return t[start:]
    return t


def stage_assets(client: dict, out_dir: Path) -> list[str]:
    """Copy the client's real logo file(s) next to the carousel HTML."""
    assets = out_dir / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    staged: list[str] = []
    pairs = [(client.get("logo_src"), client.get("logo_file"))]
    if client.get("logo_src_dark"):
        pairs.append((client.get("logo_src_dark"), client.get("logo_file_dark")))
    for src, name in pairs:
        if src and name and Path(src).is_file():
            shutil.copy2(src, assets / name)
            staged.append(name)
    return staged


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Pilot LinkedIn carousel (linkedin-studio soul, Opus 4.8)."
    )
    ap.add_argument("--client", choices=sorted(CLIENTS), required=True)
    ap.add_argument("--model", default="anthropic/claude-opus-4.8")
    ap.add_argument("--out", default=None)
    ap.add_argument("--max-tokens", type=int, default=60000)
    ap.add_argument("--temperature", type=float, default=0.6)
    ap.add_argument("--timeout", type=int, default=900)
    a = ap.parse_args()

    load_env()
    client = CLIENTS[a.client]
    out_dir = Path(a.out) if a.out else (
        ROOT / "clients" / client["slug"] / "04-production" / "pilot-linkedin-carousel"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    staged = stage_assets(client, out_dir)
    system = build_system()

    payload = {
        "model": a.model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": client["user"]},
        ],
        "max_tokens": a.max_tokens,
        "temperature": a.temperature,
        "reasoning": {"max_tokens": 1500},
    }
    req = urllib.request.Request(
        f"{API_BASE}/chat/completions", data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {or_key()}", "Content-Type": "application/json",
                 "HTTP-Referer": "https://design-hermes.local/", "X-Title": client["x_title"]},
        method="POST",
    )
    print(f"building {client['title']} with {a.model} ...", flush=True)
    started = time.time()
    try:
        with urllib.request.urlopen(req, timeout=a.timeout) as resp:
            data = json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        raise SystemExit(f"HTTP {e.code}: {e.read().decode(errors='ignore')[:400]}")
    choice = (data.get("choices") or [{}])[0]
    raw = (choice.get("message") or {}).get("content") or ""
    html = extract_html(raw)
    # Count <section> elements whose class list contains "slide" (the model may
    # add modifier classes, e.g. class="slide dark").
    slide_count = len(
        re.findall(r'<section\b[^>]*\bclass\s*=\s*["\'][^"\']*\bslide\b', html, re.I)
    )

    (out_dir / "carousel.html").write_text(html, encoding="utf-8")
    (out_dir / "raw.txt").write_text(raw, encoding="utf-8")
    meta = {
        "client": a.client, "slug": client["slug"], "model": a.model,
        "seconds": round(time.time() - started, 1),
        "finish_reason": choice.get("finish_reason"), "usage": data.get("usage"),
        "html_bytes": len(html.encode()),
        "complete": html.lower().rstrip().endswith("</html>"),
        "slide_sections_in_html": slide_count,
        "staged_assets": staged,
        "out": str(out_dir / "carousel.html"),
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2))
    print(json.dumps({k: v for k, v in meta.items() if k != "usage"}, indent=2))
    return 0 if (meta["complete"] and slide_count == 8) else 1


if __name__ == "__main__":
    raise SystemExit(main())
