#!/usr/bin/env python3
"""Pilot A (BIP): build the Automate Accelerator Business Information Pack.

Driven by the business-pack-studio soul, on a chosen model (default Opus 4.8 via
OpenRouter). 16:9 landscape deck -> single self-contained HTML -> Playwright PDF.
Embeds the cover image generated by the image lane (assets/bip-cover.png). Never
prints API keys.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERMES = Path.home() / ".hermes"
CLIENT = ROOT / "clients" / "automate-accelerator"
OUT_DIR = CLIENT / "04-production" / "pilot-v5-bip"
LOGO_SRC = CLIENT / "04-production" / "website" / "aa-logo.png"
API_BASE = "https://openrouter.ai/api/v1"

SYSTEM = """You are business-pack-studio, a senior editorial designer producing a premium Business Information Pack (BIP) - a client-ready sales/explainer PDF deck. Output ONE complete self-contained HTML document only (inline <style>, minimal vanilla <script> only if needed). No markdown, no commentary. It is rendered to a 16:9 landscape PDF via Playwright with prefer_css_page_size.

CLIENT: Automate Accelerator - Australian B2B outbound-growth and AI services. Human-led, performance-focused, AI-scaled. The outbound PARTNER, not an agency.

BIP BUILD RULES:
- 16:9 landscape deck. CSS: @page { size: 1280px 720px; margin: 0 }. Every slide is a <section class="page"> exactly 1280x720px, position:relative, overflow:hidden, with break-after:page (no break on the last). Design each page as a complete composition; do not let content overflow a page.
- Brand tokens (no other accents): --accent #F47920 (orange, CTA/highlight), --brand #412F8F (purple, depth/backgrounds), --ink #14121A, --bg #FFFFFF, --surface #F6F4FB, --muted #5A5566. Purple is the brand colour; never a generic AI purple-to-blue gradient.
- Type: Fontshare Clash Display (headings) + General Sans (body) via https://api.fontshare.com/v2/css?f[]=clash-display@600,700&f[]=general-sans@400,500,600&display=swap , Arial fallback. Large confident headings; one idea per page; headline states the takeaway.
- Brand motif: the orange double-slash "//" as a section marker, and a purple/orange dotted-matrix texture (CSS radial-gradient dots) - the signature AA pattern. Make it recognisably AA.
- COVER (page 1): full-bleed background <img src="assets/bip-cover.png" alt=""> (decorative, object-fit:cover) with ALL text as real HTML overlaid in the clean left/lower area: small logo <img src="assets/aa-logo.png">, eyebrow "Automate Accelerator // Australian B2B // Since 2021", title "More qualified meetings. Human expertise. AI where it multiplies.", and "automateaccelerator.com.au". The image is background ONLY - never bake text into it.
- ALL other text is real HTML/SVG. Monoline inline SVG icons, never emoji. WCAG AA contrast. Vary page rhythm: alternate full-bleed statement, 2-column, numbered process, big-stat, quote - no more than two card-grid pages in a row.
- Use ONLY the real proof supplied (testimonials + case-study funnel numbers). Invent no metrics, awards, logos, or quotes. Australian English, no contractions, no em-dashes.

12-PAGE INFORMATION ARCHITECTURE (one message per page):
1 Cover (as above). 2 What we do (the partner-not-agency positioning). 3 The problem. 4 Two products (Growth Engine + AI Solutions). 5 The Growth Engine system (data, email, LinkedIn, voice, landing pages, content, follow-up, CRM - as a labelled system, not a wall of text). 6 AI Solutions (document intelligence, AI triage, internal reporting, workflow automation, custom agents; plus Voice AI). 7 The data edge (we build databases, not buy them - verified decision-makers). 8 Proven results (the real case-study funnel numbers as a big-stat page). 9 What clients say (2-3 real testimonials). 10 Why Automate Accelerator (skin in the game; dedicated team under your brand; accountability). 11 Who this works for (50+ B2B industries). 12 Next step (Book a discovery call; automateaccelerator.com.au).

Return ONLY the complete HTML document, beginning with <!DOCTYPE html>."""

USER = """Build the Automate Accelerator BIP (12 pages, 16:9) using this real content.

POSITIONING: "Automate Accelerator is your outbound partner, not your outbound agency. A professional team, experienced with Australian and global decision-makers, runs your campaigns. AI multiplies what they can do. You show up to the meetings. We do the legwork." Tagline strip: "Human-led. Performance-focused. AI-scaled."

PROBLEM: "Your pipeline should not depend on referrals. Or organic growth alone. There is a better way."

TWO PRODUCTS: Growth Engine (build a predictable pipeline) and AI Solutions (reclaim your time by building AI into your operations). "One partner. Two paths. Most clients start with the Growth Engine, many add AI Solutions later."

GROWTH ENGINE SYSTEM (run by a dedicated team under your brand, nothing goes out without your approval): Data (verified decision-maker lists built from scratch, cross-verified across LinkedIn Sales Navigator, ASIC, company sites); Email + LinkedIn outreach in your voice; Voice Outreach (real calls + 24/7 inbound); Landing Pages (industry-specific, one outcome); Campaign Assets (lead magnets, articles, newsletters); Follow-up and nurturing (most sales happen after the 5th contact); CRM integration and live reporting (full transparency).

AI SOLUTIONS (built inside your business, not around it - your data, your control): Document Intelligence; AI Triage; Internal Reporting; Workflow Automation; Custom AI Agents. Plus Voice AI (natural-language calls, 24/7, books meetings). Framework: agentic workflows, guardrails, AI skills.

DATA EDGE: "We do not buy databases. We build them." Verified names, roles, companies. The right message to the wrong person is wasted - so the first job is always: reach the right person.

PROVEN RESULTS (real case-study funnels - use as big-stat figures):
- WhyCubed (Business Consulting), 60 days: 5,583 identified -> 3,769 reached -> 198 opportunities -> 103 booked.
- Growth Australia (Workplace Fitout, Sydney): 2,972 identified -> 358 reached -> 66 opportunities -> 29 booked.
- Lookup (IT & Cybersecurity), zero paid advertising: 4,189 identified -> 3,438 reached -> 705 opportunities -> 65 booked.
Active across 50+ B2B industries in Australia and globally.

TESTIMONIALS (real, verbatim - use 2-3):
- "The results have exceeded what we expected going in." - Bill McLellan, Managing Director, WhyCubed.
- "Working with AA has changed the way we approach business development entirely." - Daniel, CGO, Growth Australia.
- "AA understood our technical market immediately and built a system that actually resonated with our prospects." - Peter, CEO, Lookup.

WHY AA: "We are not an agency. We are your growth partner. The partner with skin in the game." Three differentiators: accountability (measured on meetings booked and pipeline built); a dedicated team under your brand (real people, your voice); AI that multiplies the team (scale precision and reach, never replace judgement). "One company. Six teams: strategy, data, content, AI, design, development. One account manager, one point of contact."

WHO IT WORKS FOR: B2B businesses across 50+ industries - Professional Services, IT & Cybersecurity, Business Consulting, Workplace Fitout, Marketing Services, Technology Services, Coaching, IT Services - narrow niche or broad market.

NEXT STEP: "Book a discovery call. We listen first, map your ideal buyer, and come back with a clear plan built for your market. No obligation. No sales pressure." automateaccelerator.com.au

Return ONLY the complete HTML document."""


def load_env() -> None:
    for path in [ROOT / ".env", ROOT / ".env.local", HERMES / ".env",
                 HERMES / "profiles" / "landing-page-studio" / ".env"]:
        if not path.exists():
            continue
        for line in path.read_text(errors="ignore").splitlines():
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            k, v = s.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k and k not in os.environ:
                os.environ[k] = v


def or_key() -> str:
    k = os.getenv("OPENROUTER_API_KEY") or os.getenv("OPENROUTER_KEY") or ""
    if not k.strip():
        raise SystemExit("Missing OPENROUTER_API_KEY")
    return k.strip()


def extract_html(text: str) -> str:
    if not text:
        return ""
    t = text.strip()
    if "```" in t:
        m = re.search(r"```(?:html)?\s*(.*?)```", t, re.S | re.I)
        if m:
            t = m.group(1).strip()
    low = t.lower()
    start = low.find("<!doctype")
    if start == -1:
        start = low.find("<html")
    end = low.rfind("</html>")
    if start != -1 and end != -1:
        return t[start:end + len("</html>")]
    if start != -1:
        return t[start:]
    return t


def main() -> int:
    ap = argparse.ArgumentParser(description="Pilot A BIP: AA Business Information Pack (business-pack-studio soul)")
    ap.add_argument("--model", default="anthropic/claude-opus-4.8")
    ap.add_argument("--out", default=str(OUT_DIR))
    ap.add_argument("--max-tokens", type=int, default=40000)
    ap.add_argument("--timeout", type=int, default=700)
    a = ap.parse_args()

    load_env()
    out_dir = Path(a.out)
    (out_dir / "assets").mkdir(parents=True, exist_ok=True)
    if LOGO_SRC.exists():
        shutil.copy(LOGO_SRC, out_dir / "assets" / "aa-logo.png")

    payload = {
        "model": a.model,
        "messages": [{"role": "system", "content": SYSTEM}, {"role": "user", "content": USER}],
        "max_tokens": a.max_tokens,
        "temperature": 0.6,
        "reasoning": {"max_tokens": 1500},
    }
    req = urllib.request.Request(
        f"{API_BASE}/chat/completions", data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {or_key()}", "Content-Type": "application/json",
                 "HTTP-Referer": "https://design-hermes.local/", "X-Title": "Design Hermes Pilot BIP"},
        method="POST",
    )
    print(f"building BIP with {a.model} ...", flush=True)
    started = time.time()
    try:
        with urllib.request.urlopen(req, timeout=a.timeout) as resp:
            data = json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        raise SystemExit(f"HTTP {e.code}: {e.read().decode(errors='ignore')[:400]}")
    choice = (data.get("choices") or [{}])[0]
    raw = (choice.get("message") or {}).get("content") or ""
    html = extract_html(raw)
    (out_dir / "bip.html").write_text(html, encoding="utf-8")
    (out_dir / "raw.txt").write_text(raw, encoding="utf-8")
    meta = {
        "model": a.model, "seconds": round(time.time() - started, 1),
        "finish_reason": choice.get("finish_reason"), "usage": data.get("usage"),
        "html_bytes": len(html.encode()), "complete": html.lower().rstrip().endswith("</html>"),
        "out": str(out_dir / "bip.html"),
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2))
    print(json.dumps({k: v for k, v in meta.items() if k != "usage"}, indent=2))
    return 0 if meta["complete"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
