#!/usr/bin/env python3
"""Pilot (magazine): build a client editorial feature, driven by the
print-editorial-studio soul on Opus 4.8 via OpenRouter.

A4 PORTRAIT, 4 pages -> ONE self-contained HTML -> Playwright PDF + page PNGs.
The layout is GENERATED by the soul + model (never hand-authored here). The
SYSTEM prompt is assembled from the live profile: SOUL.md + the DESIGN-OS
non-negotiables + the magazine OUTPUT CONTRACT. Run with --client {aa,inspra}.

Reuses load_env(), or_key(), extract_html() verbatim from the proven BIP
template. Never prints the API key.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERMES = Path.home() / ".hermes"
PROFILE = HERMES / "profiles" / "print-editorial-studio"
SOUL_PATH = PROFILE / "SOUL.md"
DESIGN_OS_PATH = PROFILE / "references" / "DESIGN-OS.md"
API_BASE = "https://openrouter.ai/api/v1"


# ---------------------------------------------------------------------------
# Shared helpers (verbatim from pilot_inspra_bip_generate.py).
# ---------------------------------------------------------------------------

def load_env() -> None:
    for path in [ROOT / ".env", ROOT / ".env.local", HERMES / ".env",
                 HERMES / "profiles" / "landing-page-studio" / ".env"]:
        if not path.exists():
            continue
        for line in path.read_text(errors="ignore").splitlines():
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            k, v = s.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k and k not in os.environ:
                os.environ[k] = v


def or_key() -> str:
    k = os.getenv("OPENROUTER_API_KEY") or os.getenv("OPENROUTER_KEY") or ""
    if not k.strip():
        raise SystemExit("Missing OPENROUTER_API_KEY")
    return k.strip()


def extract_html(text: str) -> str:
    if not text:
        return ""
    t = text.strip()
    if "```" in t:
        m = re.search(r"```(?:html)?\s*(.*?)```", t, re.S | re.I)
        if m:
            t = m.group(1).strip()
    low = t.lower()
    start = low.find("<!doctype")
    if start == -1:
        start = low.find("<html")
    end = low.rfind("</html>")
    if start != -1 and end != -1:
        return t[start:end + len("</html>")]
    if start != -1:
        return t[start:]
    return t


# ---------------------------------------------------------------------------
# The magazine output contract (shared across clients). Built into the SYSTEM
# prompt after the soul + the DESIGN-OS non-negotiables.
# ---------------------------------------------------------------------------

OUTPUT_CONTRACT = """
====================
OUTPUT CONTRACT - MAGAZINE EDITORIAL FEATURE
====================
Output ONE complete self-contained HTML document only (inline <style>, no external CSS, no JS needed). No markdown, no commentary. Begin with <!DOCTYPE html>. It is rendered to an A4 PORTRAIT PDF via Playwright with prefer_css_page_size and print_background.

PAGE MECHANICS (exact):
- CSS: @page { size: A4; margin: 0; }
- * { margin:0; padding:0; box-sizing:border-box; } and html,body{ -webkit-print-color-adjust:exact; print-color-adjust:exact; }
- Each page is <section class="page"> sized EXACTLY to A4: width:210mm; height:297mm; position:relative; overflow:hidden; break-after:page; (last page: break-after:auto;). Design each page as a complete composition; never let content overflow a page.
- Print-grade backgrounds must show (print_background is on). Use solid fills and CSS for all colour; do not rely on a background image for text legibility.

FOUR PAGES (exactly four <section class="page">):
1. OPENING FEATURE PAGE: a real masthead/kicker (the publication line), a strong editorial HEADLINE (the takeaway, not a slogan), a standfirst/dek (1-2 real sentences), a byline, and a hero treatment (a refined typographic or geometric opener built in CSS/SVG - NOT a photo). Focal point in the upper half.
2-3. BODY PAGES: multi-column editorial body text (2 columns, measure 60-72 characters, target 66), subheads, at least one large PULL-QUOTE set as a graphic element (quoting REAL body text only), a sidebar/callout box, and at least one data module or structured list. Use a drop-cap or a refined opener on the first body page.
4. CLOSING PAGE: a summary or clear call to action, contact details, and the publication footer.

EDITORIAL CRAFT (non-negotiable for this artifact):
- Premium long-form margins (the golden canon): inner:top:outer:bottom roughly 2:3:4:6, bottom largest. Apply a baseline rhythm (line-heights as multiples of one base unit). Folios (page numbers) and a running head/foot on body pages.
- Authored hierarchy from size + weight + colour (not size alone); three text colours maximum. ALL-CAPS labels track at least 0.06em. Use curly quotes, a real ellipsis, and tabular figures for any numbers.
- Monoline inline SVG icons only (stroke ~1.7px, currentColor). NEVER emoji. NEVER a glyph/symbol inside a class="icon" element.
- Captions on any figure in one consistent system. Real text stays real HTML/SVG; never bake a headline or number into an image.
- WCAG AA contrast on every text/background pair (body at least 4.5:1).

PAGE FIT - HARD RULE (a deterministic gate fails the document on any breach; every page is measured):
- No .page may overflow its fixed height. Every module fits inside the page with a bottom margin of at least 18mm of clear space; nothing is clipped, cut off, or pushed past the page box. No element's box may extend below or beyond its page. Set the page to overflow:hidden but design so nothing is hidden - fit the content, do not rely on clipping.
- The DATA / CAMPAIGN-FUNNEL module is a clean labelled layout: each stage value (the numeral) sits clearly ABOVE or BESIDE its label with generous spacing, and the numerals NEVER overlap the stage labels, the segment captions, or the bars. Give each stage its own column or row with fixed width; size the numerals so the longest value (for example 5,583) fits its cell without touching the neighbouring stage. Use tabular figures. If a second funnel row does not fit cleanly, drop it rather than crowd the module.
- A multi-step PROCESS list (for example Build, Test, Deploy, Optimise) must fit ENTIRELY on its page with every step and its caption fully visible. If the steps do not fit, give the process its own page, shorten the per-step copy, or reduce the step type size - never let the last step or the running foot get clipped or collide with another row.
- CLOSING PAGE footer/folio/contact block: the footer, folio (page number), and any contact details on the final page must sit FULLY inside the page with at least 18mm of clear space below them - they are the single most common element to spill a few millimetres past the page bottom. Anchor the footer with enough bottom padding (>=18mm) that its lowest pixel is well inside the 297mm box; do not pin it to the very edge. Reduce the contact-block height or lift it up the page rather than let it cross the bottom edge.
- Prefer fewer, larger, well-spaced modules over cramming. When in doubt, cut copy or move a module to another page so every page breathes and nothing overflows.

THE DISTINCTIVE 20% MOVE: carry ONE ownable editorial signature drawn from the brand (stated below) through all four pages, so an outsider could name the brand from a single page. Verify it survives to the last page.

HARD PROHIBITIONS (these fail the deterministic QA gate - do not emit any of them):
- No default AI indigo/purple hexes: #6366f1 #4f46e5 #4338ca #3730a3 #8b5cf6 #7c3aed #6d28d9 #a855f7 #9333ea #c084fc #818cf8. Use ONLY the brand tokens given below.
- No two-stop "AI" gradient that mixes a purple/violet/pink term with a blue/cyan/teal/sky term in one declaration. Prefer solid fills; a tonal single-hue gradient is fine.
- No emoji as icons; no symbol-only feature icons.
- No rounded card with a thick (>=2px) coloured left-border accent.
- No filler / lorem / placeholder copy; no placeholder image CDNs.
- INVENT NO PROOF. Use only the real numbers, quotes, names and claims supplied in the USER message verbatim. Do not introduce any percentage, "Nx" multiplier, dollar figure, client count, certification, or award that is not given. If a figure is not supplied, do not state one.

HONESTY & COPY: Australian English, no US spellings, NO contractions, NO em-dashes or en-dashes (restructure instead). Banned words: revolutionary, game-changing, streamline, empower, supercharge, seamless, unlock, elevate, leverage, cutting-edge, world-class, enterprise-grade, best-in-class, all-in-one, delve, tapestry, testament, boasts. Copy is product/editorial language describing what is literally true.

Return ONLY the complete HTML document, beginning with <!DOCTYPE html>.
"""


def build_system(soul: str, design_os: str, client_block: str) -> str:
    """SYSTEM = soul text + DESIGN-OS non-negotiables + the magazine contract + client brand block."""
    non_neg = _design_os_nonnegotiables(design_os)
    return (
        "You are print-editorial-studio. The text below is your SOUL - your craft and standards.\n\n"
        f"{soul.strip()}\n\n"
        "====================\n"
        "DESIGN-OS CONSTITUTION - NON-NEGOTIABLES (inherited; never violate)\n"
        "====================\n"
        f"{non_neg}\n\n"
        f"{client_block.strip()}\n"
        f"{OUTPUT_CONTRACT}"
    )


def _design_os_nonnegotiables(design_os: str) -> str:
    """Extract the constitution's non-negotiables + honesty sections (sections 1-2).

    Falls back to the full text if the headings are not found, so a profile edit
    never silently drops the constitution from the prompt.
    """
    start = design_os.find("## 1. Non-negotiables")
    end = design_os.find("## 3.")
    if start != -1 and end != -1 and end > start:
        return design_os[start:end].strip()
    return design_os.strip()


# ---------------------------------------------------------------------------
# Per-client brand blocks + briefs (real source-truth only).
# ---------------------------------------------------------------------------

AA_SYSTEM_BLOCK = """====================
CLIENT - AUTOMATE ACCELERATOR (brand control)
====================
Automate Accelerator is an Australian B2B growth company and outbound PARTNER (not an agency). Human-led, performance-focused, AI-scaled. "You show up to the meetings. We do the legwork." This is a thought-leadership editorial feature for their own publication, on the future of outbound: human-led, AI where it multiplies.

BRAND TOKENS (use ONLY these; no other accents):
  --accent:#F47920;  /* orange - the action/highlight colour, <=2 strong uses per page */
  --brand:#412F8F;   /* purple - brand depth, dark panels, the masthead/footer field */
  --ink:#14121A; --bg:#FFFFFF; --surface:#F6F4FB; --muted:#5A5566; --border:#E7E3F0;
Orange is the action colour; purple is brand depth. Purple is brand-specific - NEVER a generic AI purple-to-blue gradient. A tonal purple-only field is fine; never combine purple with a blue/cyan stop.

TYPE (Fontshare, web-prototype substitutes for the proprietary Gilroy): link in <head>:
  https://api.fontshare.com/v2/css?f[]=clash-display@600,700&f[]=general-sans@400,500,600&display=swap
  Clash Display for the masthead/headline/pull-quote; General Sans for body, standfirst, captions; Arial fallback. Large confident editorial headings.

DISTINCTIVE 20% MOVE (carry through all 4 pages): the orange double-slash "//" as a recurring editorial section/kicker marker, plus a purple/orange dotted-matrix texture built in CSS (repeating radial-gradient dots) used as a quiet field on opener and closer. The page must be recognisably Automate Accelerator from a single screenshot.

MASTHEAD line: "AUTOMATE ACCELERATOR // FIELD NOTES" (or similar real publication line). Footer: "Automate Accelerator  //  automateaccelerator.com.au".

PROOF DISCIPLINE (critical): The ONLY hard numbers you may print are the verbatim campaign funnels and they must be shown as the literal funnel, never converted to a percentage or an "Nx" multiplier:
  - WhyCubed (Business Consulting), 60 days: 5,583 identified, 3,769 reached, 198 opportunities, 103 booked.
  - Growth Australia (Workplace Fitout, Sydney): 2,972 identified, 358 reached, 66 opportunities, 29 booked.
  - Lookup (IT and Cybersecurity, zero paid advertising): 4,189 identified, 3,438 reached, 705 opportunities, 65 booked.
Do NOT write any standalone percentage (e.g. "98%"), any "Nx", any "$N ARR", any "N+ businesses/clients", or any award name. Do NOT invent a retention rate or a businesses-served count. If you want a data module, use the funnel numbers above exactly as listed."""

AA_USER = """Write and design the Automate Accelerator editorial feature (4 pages, A4 portrait) using ONLY the real content below.

PUBLICATION / KICKER: "Automate Accelerator // Field Notes" - an in-house editorial on B2B growth.

HEADLINE (the takeaway): something true and editorial along the lines of "The legwork is the strategy" or "Why outbound is a team sport again" - a confident editorial headline, not a tagline. Choose one.
STANDFIRST (dek): draw from the real positioning - a professional team runs your campaigns and AI multiplies what they can do; you show up to the meetings, we do the legwork.
BYLINE: "By the Automate Accelerator growth team".

THE ARGUMENT (real, for the body - paraphrase faithfully, do not invent):
- Your pipeline should not depend on referrals or organic growth alone. There is a better way, and it is built, not bought.
- Automate Accelerator is your outbound partner, not your outbound agency. A professional team, experienced with Australian and global decision-makers, runs your campaigns. AI multiplies what they can do, never replaces the judgement.
- The first job in every engagement is reaching the right person. The right message to the wrong person is wasted time and resources. So the data is built, not bought: verified names, roles and companies, cross-verified across LinkedIn Sales Navigator, ASIC records and company websites. No shortcuts, no shared lists, no buying a database.
- The Growth Engine runs as one system under your brand, nothing goes out without your approval: data, email and LinkedIn in your voice, voice outreach, landing pages, campaign assets, follow-up and nurture, CRM and live reporting. Most sales happen after the fifth contact, so the follow-up is where pipeline is won.
- AI is built inside your business, not around it - your data, your control: document intelligence, AI triage, internal reporting, workflow automation, custom agents, and Voice AI that handles calls 24/7 and books meetings.
- The difference is accountability and skin in the game: one company, six teams (strategy, data, content, AI, design, development), one account manager, one point of contact.

PULL-QUOTE (must be a verbatim phrase that ALSO appears in your body text): use "You show up to the meetings. We do the legwork." OR "The right message to the wrong person is wasted time and resources." - whichever you place in the body, quote exactly.

DATA MODULE (use the verbatim funnel - this is the only hard data; present as a labelled four-stage funnel, never a percentage):
  WhyCubed, Business Consulting, 60 days: 5,583 identified, 3,769 reached, 198 opportunities, 103 booked.
  (You may add Lookup, IT and Cybersecurity, zero paid advertising: 4,189 identified, 3,438 reached, 705 opportunities, 65 booked - as a second row if a page needs it.)

SIDEBAR / CALLOUT (real): "Built, not bought" - the four verification sources (LinkedIn Sales Navigator, ASIC records, company websites, specialist registries) as a short labelled list; nothing enters a campaign unverified.

TESTIMONIAL (real, verbatim, attribute exactly): "The results have exceeded what we expected going in." - Bill McLellan, Managing Director, WhyCubed.

CLOSING PAGE / CTA: "Book a discovery call. We listen first, map your ideal buyer, and come back with a clear plan built for your market. No obligation. No sales pressure." Footer: Automate Accelerator // automateaccelerator.com.au.

Return ONLY the complete HTML document."""

INSPRA_SYSTEM_BLOCK = """====================
CLIENT - INSPRA AI (brand control)
====================
Inspra AI (a trading brand of Genius365) builds, deploys and optimises Voice AI agents that handle phone calls 24/7 with natural, professional Australian conversations, so businesses scale without scaling headcount. Melbourne, ISO 27001 certified. This is a thought-leadership editorial feature on voice AI for Australian business: never miss a call.

BRAND TOKENS (use ONLY these; no other accents):
  --accent:#39E100;  /* signature green - the voice/soundwave signal colour, highlights, key numbers */
  --ink:#1A1A1A; --bg:#FFFFFF; --dark:#121212; /* dark editorial panels */ --surface:#F4F7F2; --muted:#5A5F58;
Green is the brand signal colour, used deliberately on dark and on white. Never a generic AI purple-to-blue gradient; green only as the accent.

TYPE (Fontshare, web-prototype substitute for the brand font Calibri): link in <head>:
  https://api.fontshare.com/v2/css?f[]=switzer@500,600,700&f[]=general-sans@400,500,600&display=swap
  Switzer for the masthead/headline/pull-quote; General Sans for body, standfirst, captions; Arial fallback. Clean, confident, modern editorial.

DISTINCTIVE 20% MOVE (carry through all 4 pages): a green soundwave / waveform line and green signal dots (the voice-AI signature) used as the masthead rule, section dividers and the hero motif. The page must be recognisably Inspra from a single screenshot.

MASTHEAD line: "INSPRA AI // SIGNAL" (or similar real publication line). Footer: "Inspra AI  //  inspra.ai".

PROOF DISCIPLINE (critical): the ONLY hard claims you may print, verbatim, are: 40% increase in conversion; 15x more call outputs; 40% cost reduction in operations; 24/7 operation; 350+ enterprises on the platform; ISO 27001 certified. Contact: 1300 467772, hello@inspra.ai, Suite 1, Level 10/3 Bowen Crescent, Melbourne VIC 3004. Do NOT invent any other metric, percentage, multiplier, client count, award or certification."""

INSPRA_USER = """Write and design the Inspra AI editorial feature (4 pages, A4 portrait) using ONLY the real content below.

PUBLICATION / KICKER: "Inspra AI // Signal" - an in-house editorial on voice AI for Australian business.

HEADLINE (the takeaway): an editorial line such as "Never miss a call again" or "The phone is still the front door" - confident and editorial, not a slogan. Choose one.
STANDFIRST (dek): voice AI agents that handle calls 24/7 with natural, professional Australian conversations, so a business scales without scaling headcount.
BYLINE: "By the Inspra AI team".

THE ARGUMENT (real, for the body - paraphrase faithfully, do not invent):
- Every missed call is a missed customer. Phone-based workflows are expensive to staff, quality is inconsistent, and calls go unanswered after hours and at the weekend.
- Inspra builds, deploys and optimises Voice AI agents that handle calls 24/7 with natural, professional Australian conversations. You keep the human touch where it matters; the agents handle the volume. You scale without scaling headcount.
- Ready-to-deploy industry agents exist for Real Estate, Legal Services, Dental Practice, and Plumbing and Trades.
- The platform spans Prospecting, Customer Support, Appointment Booking, a Smart Dashboard, Call IQ (auto summaries and sentiment analysis), an AI Chatbot, and a Data Bank.
- How it works: Build (custom agents configured for your business and flows), Test (battle-tested with real scenarios before go-live), Deploy (go-live with monitoring, call recording and analytics), Optimise (continuous improvement from real call data).
- Why Inspra: ISO 27001 certified for voice data; Australian-based with Australian voice profiles; principle-based prompts rather than rigid scripts; multi-platform (VAPI, Retell AI, LiveKit), never locked to one provider; scales from 10 to 10,000 calls per day, 24/7.

PULL-QUOTE (must be a verbatim phrase that ALSO appears in your body text): use "Every missed call is a missed customer." OR "You scale without scaling headcount." - whichever you place in the body, quote exactly.

DATA MODULE (use these exact figures, present as a clean stat band): 40% increase in conversion; 15x more call outputs; 40% cost reduction in operations; 24/7 operation; 350+ enterprises on the platform; ISO 27001 certified.

SIDEBAR / CALLOUT (real): "How it works" - Build, Test, Deploy, Optimise as a short numbered list with one real line each.

CLOSING PAGE / CTA: "Book a demo." Contact: 1300 467772, hello@inspra.ai, Suite 1, Level 10/3 Bowen Crescent, Melbourne VIC 3004. Footer: Inspra AI // inspra.ai.

Return ONLY the complete HTML document."""


CLIENTS = {
    "aa": {
        "slug": "automate-accelerator",
        "label": "Automate Accelerator",
        "system_block": AA_SYSTEM_BLOCK,
        "user": AA_USER,
        # Source-truth the QA gate scans against (must contain every figure used).
        "source_truth": ROOT / "clients" / "automate-accelerator" / "02-source-truth",
    },
    "inspra": {
        "slug": "inspra-ai",
        "label": "Inspra AI",
        "system_block": INSPRA_SYSTEM_BLOCK,
        "user": INSPRA_USER,
        "source_truth": ROOT / "clients" / "inspra-ai" / "02-source-truth",
    },
}


def main() -> int:
    ap = argparse.ArgumentParser(description="Pilot magazine: client editorial feature (print-editorial-studio soul)")
    ap.add_argument("--client", required=True, choices=sorted(CLIENTS), help="aa or inspra")
    ap.add_argument("--model", default="anthropic/claude-opus-4.8")
    ap.add_argument("--out", default=None)
    ap.add_argument("--max-tokens", type=int, default=60000)
    ap.add_argument("--temperature", type=float, default=0.6)
    ap.add_argument("--timeout", type=int, default=900)
    a = ap.parse_args()

    load_env()
    cfg = CLIENTS[a.client]
    out_dir = Path(a.out) if a.out else (
        ROOT / "clients" / cfg["slug"] / "04-production" / "pilot-magazine"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    soul = SOUL_PATH.read_text(encoding="utf-8")
    design_os = DESIGN_OS_PATH.read_text(encoding="utf-8")
    system = build_system(soul, design_os, cfg["system_block"])
    user = cfg["user"]

    payload = {
        "model": a.model,
        "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
        "max_tokens": a.max_tokens,
        "temperature": a.temperature,
        "reasoning": {"max_tokens": 1500},
    }
    req = urllib.request.Request(
        f"{API_BASE}/chat/completions", data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {or_key()}", "Content-Type": "application/json",
                 "HTTP-Referer": "https://design-hermes.local/", "X-Title": f"Design Hermes Pilot Magazine {cfg['label']}"},
        method="POST",
    )
    print(f"building {cfg['label']} magazine with {a.model} ...", flush=True)
    started = time.time()
    try:
        with urllib.request.urlopen(req, timeout=a.timeout) as resp:
            data = json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        raise SystemExit(f"HTTP {e.code}: {e.read().decode(errors='ignore')[:400]}")
    choice = (data.get("choices") or [{}])[0]
    raw = (choice.get("message") or {}).get("content") or ""
    html = extract_html(raw)
    # Count any element whose class list contains the `page` token, so modifier
    # classes (e.g. "page recto", "page p1") match the same way .querySelectorAll('.page') does.
    page_count = len(re.findall(r'class="[^"]*\bpage\b[^"]*"', html))
    (out_dir / "magazine.html").write_text(html, encoding="utf-8")
    (out_dir / "raw.txt").write_text(raw, encoding="utf-8")
    meta = {
        "client": a.client, "label": cfg["label"], "model": a.model,
        "seconds": round(time.time() - started, 1),
        "finish_reason": choice.get("finish_reason"), "usage": data.get("usage"),
        "html_bytes": len(html.encode()),
        "page_sections": page_count,
        "complete": html.lower().rstrip().endswith("</html>"),
        "out": str(out_dir / "magazine.html"),
        "system_prompt_chars": len(system),
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2))
    print(json.dumps({k: v for k, v in meta.items() if k != "usage"}, indent=2))
    return 0 if (meta["complete"] and page_count == 4) else 1


if __name__ == "__main__":
    raise SystemExit(main())
