#!/usr/bin/env python3
"""Pilot: LinkedIn personal-profile BANNERS, driven by the linkedin-studio soul.

The banner is GENERATED by the model from the profile soul + constitution as the
system prompt (exactly like the BIP pilots) - this script does not hand-author the
design. It loads the OpenRouter key, POSTs a SYSTEM + USER message to
/chat/completions on Opus 4.8, extracts the HTML, and saves html + raw.txt +
meta.json. Render + QA are separate steps (Playwright, qa_antislop).

  uv run --no-project python factory/scripts/pilot_linkedin_banner_generate.py --client aa
  uv run --no-project python factory/scripts/pilot_linkedin_banner_generate.py --client inspra

Reuses load_env(), or_key(), extract_html() verbatim from pilot_inspra_bip_generate.py.
Never prints the API key.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERMES = Path.home() / ".hermes"
PROFILE = HERMES / "profiles" / "linkedin-studio"
API_BASE = "https://openrouter.ai/api/v1"


# --- verbatim from pilot_inspra_bip_generate.py -----------------------------

def load_env() -> None:
    for path in [ROOT / ".env", ROOT / ".env.local", HERMES / ".env",
                 HERMES / "profiles" / "landing-page-studio" / ".env"]:
        if not path.exists():
            continue
        for line in path.read_text(errors="ignore").splitlines():
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            k, v = s.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k and k not in os.environ:
                os.environ[k] = v


def or_key() -> str:
    k = os.getenv("OPENROUTER_API_KEY") or os.getenv("OPENROUTER_KEY") or ""
    if not k.strip():
        raise SystemExit("Missing OPENROUTER_API_KEY")
    return k.strip()


def extract_html(text: str) -> str:
    if not text:
        return ""
    t = text.strip()
    if "```" in t:
        m = re.search(r"```(?:html)?\s*(.*?)```", t, re.S | re.I)
        if m:
            t = m.group(1).strip()
    low = t.lower()
    start = low.find("<!doctype")
    if start == -1:
        start = low.find("<html")
    end = low.rfind("</html>")
    if start != -1 and end != -1:
        return t[start:end + len("</html>")]
    if start != -1:
        return t[start:]
    return t


# --- system prompt: soul + constitution non-negotiables + output contract ---

def read_profile_text() -> tuple[str, str, str]:
    soul = (PROFILE / "SOUL.md").read_text(encoding="utf-8")
    const = (PROFILE / "references" / "DESIGN-OS.md").read_text(encoding="utf-8")
    sop = (PROFILE / "skills" / "linkedin-asset-production" / "SKILL.md").read_text(encoding="utf-8")
    return soul, const, sop


OUTPUT_CONTRACT = """
====================  OUTPUT CONTRACT (LinkedIn personal-profile banner)  ====================
Produce ONE strong personal-profile banner as ONE self-contained HTML document. Output ONLY the
HTML, beginning with <!DOCTYPE html>. No markdown fences, no commentary.

GEOMETRY (the law - get this wrong and the asset is invisible):
- The root banner element is EXACTLY 1584px wide x 396px tall, position:relative, overflow:hidden.
  Use a fixed-size container, e.g. .banner { width:1584px; height:396px; position:relative; overflow:hidden }.
  Set <body> margin:0 and background to match so the screenshot has no stray edge.
- AVATAR DEAD-ZONE: the round profile photo overlaps the LOWER-LEFT. Keep ALL essential content
  (headline, value line, handle, logo) clear of a ~270px circle anchored to the lower-left corner,
  and keep the far-left third visually quiet. Anchor the headline / value line / handle to the
  CENTRE-RIGHT or upper area. Nothing important below the midline on the left.
- This renders to PNG; @page is not needed.

CONTENT (all REAL HTML/SVG text - never baked into an image):
- A real headline (name or role line), a one-line value proposition, and a handle / domain.
- Lay them as live HTML or inline SVG <text>. The brand signature colour LEADS. WCAG AA contrast
  on every text run against whatever sits behind it (>=4.5:1 body, >=3:1 large).
- Monoline inline SVG icons only (1.6-1.8px stroke, currentColor). NEVER emoji.
- Embed the client logo via the <img> path given in the brief (it sits relative to the HTML file).
- Keep it to one idea: who this is + the one-line value. No paragraphs, no card grids, no clutter.

BACKGROUND (optional, decorative only):
- You MAY reference a full-bleed textless background image as <img src="assets/bg.jpg" ... > behind
  the text IF the brief says one was generated. It carries NO text/logo/face. If no bg is provided,
  build the background from brand CSS (solid brand colour, the brand motif, subtle dotted-matrix or
  waveform) - never a generic two-stop purple/blue/cyan AI gradient.

HONESTY (non-negotiable, gate-enforced):
- Use ONLY the supplied real facts. Invent NO metrics, percentages, "Nx", dollar figures, client
  names, awards, testimonials. A banner is a value-prop surface: prefer NO numeric proof claims at all.
  Do not write any "<number>%", "<number>x", or "<number>+ businesses/clients" unless the brief lists
  it verbatim as allowed. Australian English, no US spellings, NO contractions, NO em/en-dash
  punctuation (restructure instead). Avoid the banned-word list in the constitution.

DISTINCTIVE MOVE (the soul test): land ONE ownable move so an outsider could name the brand from the
banner alone (the brief states it). It must survive to the final banner.

Return ONLY the complete HTML document, beginning with <!DOCTYPE html>.
""".strip()


def build_system() -> str:
    soul, const, sop = read_profile_text()
    return (
        "You are linkedin-studio. Below is your SOUL, the DESIGN-OS constitution you inherit, and "
        "your LinkedIn asset-production SOP. Design strictly within them: the constitution's "
        "non-negotiables (section 1), honesty and banned-words (section 2), the 7 anti-slop sins "
        "(section 3) and the QA contract are the floor and are NOT overridable. Then follow the "
        "OUTPUT CONTRACT exactly.\n\n"
        "================  SOUL (linkedin-studio)  ================\n" + soul.strip() + "\n\n"
        "================  CONSTITUTION (DESIGN-OS, inherited)  ================\n" + const.strip() + "\n\n"
        "================  SOP (linkedin-asset-production)  ================\n" + sop.strip() + "\n\n"
        + OUTPUT_CONTRACT
    )


# --- per-client briefs (real facts only) ------------------------------------

CLIENTS: dict[str, dict] = {
    "aa": {
        "slug": "automate-accelerator",
        "title": "Automate Accelerator LinkedIn banner",
        "x_title": "Hermes Pilot AA LinkedIn Banner",
        "logo_img": "assets/aa-logo.png",
        "bg_prompt": (
            "1584x396 wide banner background texture, Automate Accelerator brand palette of warm "
            "orange #F47920 and deep purple #412F8F on a near-white field, an abstract dotted-matrix "
            "and concentric-ring motif of small dots drifting from the centre-right toward the right "
            "edge, large calm empty negative space across the entire LOWER-LEFT quadrant and the "
            "far-left third, focal interest centre-right, professional B2B, flat vector, no text, no "
            "letters, no numbers, no logos, no faces, no people, NO purple-to-blue or blue-to-cyan "
            "gradient, no neon, generous white space"
        ),
        "user": """Build ONE Automate Accelerator personal-profile LinkedIn banner (1584x396) using ONLY this real content.

WHO / VOICE: Automate Accelerator - an Australian B2B growth company and outbound partner (not an agency). Founder-credible, direct, no fluff, accountable. Australian English, no contractions, no dashes.

LOGO: embed <img src="assets/aa-logo.png"> at a tidy height (about 36-44px, auto width; the logo is a wide horizontal lockup 1454x360). Place it centre-right or upper area, clear of the lower-left avatar circle. CRITICAL: this master logo is the PURPLE "utomate" wordmark plus orange marks on a TRANSPARENT background, so it is nearly invisible on a purple field. It MUST sit on a LIGHT surface for contrast - put it inside a small white or near-white (#F7F4FF) rounded plate / chip with comfortable padding (about 12-16px) so the purple wordmark reads clearly at WCAG AA. Never place the bare logo directly on the purple field.

EXACT TEXT TO USE (real, from source-truth - you may pick the strongest, do not invent new claims):
- Headline (pick one, verbatim): "More qualified meetings. Human expertise. AI where it multiplies." OR "You show up to the meetings. We do the legwork."
- Value line / tagline (verbatim): "Human-led. Performance-focused. AI-scaled."
- Handle / domain: "automateaccelerator.com.au"
- Optional descriptor eyebrow (verbatim): "Australian B2B growth partner" or "Your outbound partner, not your outbound agency."

DO NOT put any numbers, percentages, "Nx", award names or client counts on the banner. No metrics. Value proposition only.

BRAND: orange #F47920 is the ACTION/signature colour (use it as the lead accent, <=2 strong uses); purple #412F8F is brand depth (good as the dark text/background field). White space is a design asset. Headings on the Clash Display / General Sans Fontshare stack (https://api.fontshare.com/v2/css?f[]=clash-display@600,700&f[]=general-sans@400,500,600&display=swap), Arial fallback. NEVER a generic AI purple-to-blue gradient. No emoji icons.

A textless brand background has been generated at assets/bg.jpg - reference it as a full-bleed decorative <img> behind the real HTML text, OR build the field from brand CSS if it reads cleaner. Either way ALL text is real HTML/SVG.

DISTINCTIVE MOVE: the orange "//" double-slash section marker plus the purple/orange dotted-matrix texture, so the banner is unmistakably Automate Accelerator from a single screenshot.

Return ONLY the complete HTML document.""",
    },
    "inspra": {
        "slug": "inspra-ai",
        "title": "Inspra AI LinkedIn banner",
        "x_title": "Hermes Pilot Inspra LinkedIn Banner",
        "logo_img": "assets/inspra-logo-light.png",
        "bg_prompt": (
            "1584x396 wide banner background texture, near-black charcoal #121212 field with a single "
            "bright signal-green #39E100 monoline soundwave / audio waveform sweeping across the "
            "centre-right toward the right edge, a few small green signal dots, large calm empty "
            "negative space across the entire LOWER-LEFT quadrant and the far-left third, focal "
            "interest centre-right, premium enterprise voice-AI feel, flat vector, no text, no "
            "letters, no numbers, no logos, no faces, no people, NO purple, NO blue-to-cyan gradient, "
            "single green accent only on dark"
        ),
        "user": """Build ONE Inspra AI personal-profile LinkedIn banner (1584x396) using ONLY this real content.

WHO / VOICE: Inspra AI (by Genius365) - Voice AI agents for Australian businesses; build, deploy and optimise Voice AI agents that handle calls 24/7 with natural, professional Australian conversations. Melbourne. Direct, enterprise-credible. Australian English, no contractions, no dashes.

LOGO: embed <img src="assets/inspra-logo-light.png"> (the LIGHT logo, for a dark banner) at a tidy height (about 34-40px, auto width; source 300x81). Place it centre-right or upper area, clear of the lower-left avatar circle.

EXACT TEXT TO USE (real, from source-truth - do not invent):
- Headline (pick one, verbatim or close paraphrase staying factual): "AI voice agents that handle your calls. Around the clock." OR "Voice AI agents for Australian business."
- Value line (verbatim): "Scale without scaling headcount." OR "We build, deploy and optimise Voice AI agents that handle your calls."
- Handle / domain: "inspra.ai"
- ALLOWED proof badge (the ONLY proof phrase permitted, must be written EXACTLY): "ISO 27001 certified". You may also write the literal phrase "24/7". Nothing else numeric.

DO NOT write "40%", "15x", "350+ enterprises", or any other metric on the banner - those are not permitted here. Value proposition only, plus the allowed "ISO 27001 certified" and "24/7".

BRAND: signal green #39E100 is the signature colour and LEADS (highlights, the soundwave motif, the handle); ink #1A1A1A / dark #121212 field; white text. Green on dark and white on dark must pass WCAG AA. Switzer + General Sans Fontshare stack (https://api.fontshare.com/v2/css?f[]=switzer@600,700&f[]=general-sans@400,500,600&display=swap), Arial fallback. NEVER a purple or purple-to-blue/cyan AI gradient. No emoji icons.

A textless brand background has been generated at assets/bg.jpg - reference it as a full-bleed decorative <img> behind the real HTML text, OR build the dark field + green soundwave from brand CSS if it reads cleaner. Either way ALL text is real HTML/SVG.

DISTINCTIVE MOVE: the green monoline soundwave / waveform line with green signal dots (the voice-AI signature) leading across the banner, so it is unmistakably Inspra from a single screenshot.

Return ONLY the complete HTML document.""",
    },
}


def main() -> int:
    ap = argparse.ArgumentParser(description="Pilot LinkedIn banner (linkedin-studio soul)")
    ap.add_argument("--client", required=True, choices=sorted(CLIENTS))
    ap.add_argument("--model", default="anthropic/claude-opus-4.8")
    ap.add_argument("--out", default=None)
    ap.add_argument("--max-tokens", type=int, default=50000)
    ap.add_argument("--temperature", type=float, default=0.6)
    ap.add_argument("--timeout", type=int, default=700)
    a = ap.parse_args()

    spec = CLIENTS[a.client]
    out_dir = Path(a.out) if a.out else (
        ROOT / "clients" / spec["slug"] / "04-production" / "pilot-linkedin-banner"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    load_env()
    system = build_system()
    payload = {
        "model": a.model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": spec["user"]},
        ],
        "max_tokens": a.max_tokens,
        "temperature": a.temperature,
        "reasoning": {"max_tokens": 1500},
    }
    req = urllib.request.Request(
        f"{API_BASE}/chat/completions", data=json.dumps(payload).encode(),
        headers={
            "Authorization": f"Bearer {or_key()}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://design-hermes.local/",
            "X-Title": spec["x_title"],
        },
        method="POST",
    )
    print(f"building {spec['title']} with {a.model} ...", flush=True)
    started = time.time()
    try:
        with urllib.request.urlopen(req, timeout=a.timeout) as resp:
            data = json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        raise SystemExit(f"HTTP {e.code}: {e.read().decode(errors='ignore')[:400]}")
    choice = (data.get("choices") or [{}])[0]
    raw = (choice.get("message") or {}).get("content") or ""
    html = extract_html(raw)
    (out_dir / "banner.html").write_text(html, encoding="utf-8")
    (out_dir / "raw.txt").write_text(raw, encoding="utf-8")

    usage = data.get("usage") or {}
    cost = usage.get("cost")
    meta = {
        "client": a.client,
        "slug": spec["slug"],
        "model": a.model,
        "seconds": round(time.time() - started, 1),
        "finish_reason": choice.get("finish_reason"),
        "usage": usage,
        "cost_usd": cost,
        "html_bytes": len(html.encode()),
        "complete": html.lower().rstrip().endswith("</html>"),
        "out": str(out_dir / "banner.html"),
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2))
    print(json.dumps({k: v for k, v in meta.items() if k != "usage"}, indent=2))
    return 0 if meta["complete"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
